import json
from sqlalchemy.orm import Session
from .models import Question


def seed_questions(db: Session):
    if db.query(Question).count() > 0:
        return

    questions = [

        # ══ TIER 1 — Very Easy ══

        dict(topic="Java Basics", difficulty=1,
             prompt="Which of these is a valid way to declare an integer variable in Java?",
             options=["int x = 5;", "integer x = 5;", "Int x = 5;", "x = 5;"],
             correct_answer="int x = 5;",
             hint_1="Java primitive types are all lowercase.",
             hint_2="The integer primitive type is written as 'int' — not 'integer' or 'Int'.",
             explanation="Java's integer primitive is 'int' (lowercase). You must also declare the type before the variable name — x = 5 alone is not valid."),

        dict(topic="Java Basics", difficulty=1,
             prompt="What is the correct way to print 'Hello' to the console in Java?",
             options=["System.out.println(\"Hello\");", "print(\"Hello\");", "console.log(\"Hello\");", "echo \"Hello\";"],
             correct_answer="System.out.println(\"Hello\");",
             hint_1="Java uses the System class for console output.",
             hint_2="The full method is System.out.println().",
             explanation="In Java, console output is done through System.out.println(). print() exists in Python, console.log() in JavaScript, and echo in PHP/Bash — none are valid Java."),

        dict(topic="Java Basics", difficulty=1,
             prompt="What data type stores a single character like 'A' in Java?",
             options=["char", "String", "letter", "character"],
             correct_answer="char",
             hint_1="Java has a primitive type specifically for single characters.",
             hint_2="It uses single quotes: char c = 'A';",
             explanation="'char' is Java's primitive for a single character, written with single quotes. String holds a sequence of characters — char holds exactly one."),

        dict(topic="Java Basics", difficulty=1,
             prompt="Which of these is a valid boolean value in Java?",
             options=["true", "True", "TRUE", "1"],
             correct_answer="true",
             hint_1="Java boolean literals are case-sensitive.",
             hint_2="Booleans in Java are strictly lowercase: true and false.",
             explanation="Java's boolean literals are lowercase true and false. Unlike C or Python, the integer 1 is not treated as true in Java — types are strictly enforced."),

        dict(topic="Control Flow", difficulty=1,
             prompt="What does this print?\n\nif (true) {\n    System.out.println(\"Yes\");\n} else {\n    System.out.println(\"No\");\n}",
             options=["Yes", "No", "true", "Nothing"],
             correct_answer="Yes",
             hint_1="The condition is the literal value true.",
             hint_2="When a condition is always true, the if-branch always executes.",
             explanation="The condition is the boolean literal true, so the if-branch always runs. The else branch is unreachable here."),

        dict(topic="Control Flow", difficulty=1,
             prompt="How many times does this loop print?\n\nfor (int i = 0; i < 3; i++) {\n    System.out.println(i);\n}",
             options=["3", "2", "4", "0"],
             correct_answer="3",
             hint_1="Count the values i takes: 0, 1, 2...",
             hint_2="The loop stops when i becomes 3 because 3 < 3 is false.",
             explanation="i runs through values 0, 1, 2 — three iterations. When i becomes 3, the condition 3 < 3 is false so the loop exits without printing."),

        dict(topic="Control Flow", difficulty=1,
             prompt="What keyword exits a loop immediately in Java?",
             options=["break", "exit", "stop", "return"],
             correct_answer="break",
             hint_1="This keyword breaks out of the nearest enclosing loop.",
             hint_2="break jumps execution past the closing brace of the loop.",
             explanation="break immediately exits the enclosing loop. return exits the whole method. exit and stop are not Java keywords."),

        dict(topic="Control Flow", difficulty=1,
             prompt="What does this print?\n\nint x = 3;\nif (x > 5) {\n    System.out.println(\"Big\");\n} else {\n    System.out.println(\"Small\");\n}",
             options=["Small", "Big", "3", "Nothing"],
             correct_answer="Small",
             hint_1="Evaluate whether 3 > 5 is true or false.",
             hint_2="3 > 5 is false, so the else branch runs.",
             explanation="3 > 5 is false, so the else branch executes and prints Small. The if-branch is skipped entirely."),

        dict(topic="Methods & Arrays", difficulty=1,
             prompt="What is the index of the first element in a Java array?",
             options=["0", "1", "-1", "It depends on the array"],
             correct_answer="0",
             hint_1="Java arrays are zero-indexed.",
             hint_2="The first element is always at position 0, regardless of array size.",
             explanation="Java arrays start at index 0. A 3-element array has valid indices 0, 1, and 2. Accessing index 3 would throw an ArrayIndexOutOfBoundsException."),

        dict(topic="Methods & Arrays", difficulty=1,
             prompt="What does this print?\n\nint[] a = {4, 8, 2};\nSystem.out.println(a.length);",
             options=["3", "2", "4", "0"],
             correct_answer="3",
             hint_1=".length gives the total number of elements in the array.",
             hint_2="The array has three elements: 4, 8, 2.",
             explanation="a.length is a field (not a method) that stores the number of elements. The array {4, 8, 2} has 3 elements, so it prints 3."),

        dict(topic="Methods & Arrays", difficulty=1,
             prompt="What return type should a method have if it returns nothing?",
             options=["void", "null", "empty", "None"],
             correct_answer="void",
             hint_1="There is a specific keyword in Java meaning 'returns nothing'.",
             hint_2="Written as: void methodName() { }",
             explanation="void tells the compiler the method doesn't return a value. null is a value, not a type. None and empty don't exist as return types in Java."),

        dict(topic="OOP", difficulty=1,
             prompt="What keyword creates a new object in Java?",
             options=["new", "create", "object", "make"],
             correct_answer="new",
             hint_1="This keyword allocates memory for a new object instance.",
             hint_2="Syntax: ClassName obj = new ClassName();",
             explanation="The new keyword allocates heap memory and calls the class constructor to initialise the object. create, make, and object are not Java keywords."),

        dict(topic="OOP", difficulty=1,
             prompt="What is a class in Java?",
             options=["A blueprint for creating objects", "A running instance of a program", "A type of loop", "A built-in method"],
             correct_answer="A blueprint for creating objects",
             hint_1="Think of a class as a template.",
             hint_2="Objects are instances created from that template.",
             explanation="A class defines the fields and methods that its objects share. You can create many objects (instances) from one class, each with their own data."),

        # ══ TIER 2 — Easy ══

        dict(topic="Java Basics", difficulty=2,
             prompt="What is the output?\n\nint x = 5;\nint y = 2;\nSystem.out.println(x % y);",
             options=["1", "2", "0", "2.5"],
             correct_answer="1",
             hint_1="% is the modulo operator — it returns the remainder after division.",
             hint_2="5 divided by 2 is 2 with remainder 1.",
             explanation="The % operator computes the remainder of integer division. 5 = (2 × 2) + 1, so the remainder is 1."),

        dict(topic="Java Basics", difficulty=2,
             prompt="What is the output?\n\nint x = 7;\nSystem.out.println(x++);\nSystem.out.println(x);",
             options=["7 then 8", "8 then 8", "7 then 7", "8 then 9"],
             correct_answer="7 then 8",
             hint_1="x++ is post-increment: it returns the current value first, then increments.",
             hint_2="The first print uses x=7. x then becomes 8. The second print shows 8.",
             explanation="Post-increment (x++) evaluates to the current value before incrementing. So println sees 7, then x becomes 8. The second println prints the updated value: 8."),

        dict(topic="Java Basics", difficulty=2,
             prompt="What is the result of 5 / 2 in Java when both are ints?",
             options=["2", "2.5", "3", "2.0"],
             correct_answer="2",
             hint_1="Integer division truncates — it drops the decimal part entirely.",
             hint_2="Java does not round; it cuts off anything after the decimal point.",
             explanation="When both operands are int, Java does integer division. The result is truncated toward zero: 5 / 2 = 2 (not 2.5 or 3). To get 2.5, at least one operand must be a double or float."),

        dict(topic="Java Basics", difficulty=2,
             prompt="What is the output?\n\nString s = \"Hello\";\nSystem.out.println(s.length());",
             options=["5", "6", "4", "Error"],
             correct_answer="5",
             hint_1=".length() counts the number of characters in the string.",
             hint_2="H, e, l, l, o — count them.",
             explanation="String.length() returns the character count. \"Hello\" has 5 characters. Note: for arrays you use .length (no parentheses); for Strings you use .length()."),

        dict(topic="Control Flow", difficulty=2,
             prompt="What is the output?\n\nint x = 4;\nif (x % 2 == 0) {\n    System.out.println(\"Even\");\n} else {\n    System.out.println(\"Odd\");\n}",
             options=["Even", "Odd", "4", "0"],
             correct_answer="Even",
             hint_1="Evaluate x % 2 when x = 4.",
             hint_2="4 % 2 = 0, and 0 == 0 is true.",
             explanation="4 divided by 2 has remainder 0, so x % 2 == 0 is true. The if-branch executes and prints Even."),

        dict(topic="Control Flow", difficulty=2,
             prompt="What does this print?\n\nfor (int i = 1; i <= 3; i++) {\n    System.out.print(i + \" \");\n}",
             options=["1 2 3", "0 1 2", "1 2 3 4", "1 2"],
             correct_answer="1 2 3",
             hint_1="i starts at 1 and runs while i <= 3.",
             hint_2="i takes values 1, 2, 3 before the condition becomes false.",
             explanation="The loop runs for i = 1, 2, 3. print() (not println) keeps output on one line. After i=3, i increments to 4 and 4 <= 3 is false, so the loop ends."),

        dict(topic="Control Flow", difficulty=2,
             prompt="What does this print?\n\nint i = 0;\nwhile (i < 3) {\n    System.out.print(i + \" \");\n    i++;\n}",
             options=["0 1 2", "1 2 3", "0 1 2 3", "infinite loop"],
             correct_answer="0 1 2",
             hint_1="The loop runs while i < 3, starting at 0.",
             hint_2="When i becomes 3, the condition fails and the loop exits.",
             explanation="i starts at 0, prints 0, increments. Repeats for 1 and 2. After i becomes 3, 3 < 3 is false so the loop ends. Output: 0 1 2."),

        dict(topic="Methods & Arrays", difficulty=2,
             prompt="What is the output?\n\nint[] a = {10, 20, 30};\nSystem.out.println(a[1]);",
             options=["20", "10", "30", "1"],
             correct_answer="20",
             hint_1="Arrays are zero-indexed.",
             hint_2="Index 0 = 10, index 1 = 20, index 2 = 30.",
             explanation="a[1] accesses index 1. With zero-indexing: a[0]=10, a[1]=20, a[2]=30. So a[1] is 20."),

        dict(topic="Methods & Arrays", difficulty=2,
             prompt="What does this method return?\n\nstatic int square(int n) {\n    return n * n;\n}\n\nSystem.out.println(square(5));",
             options=["25", "10", "5", "55"],
             correct_answer="25",
             hint_1="The method body returns n * n.",
             hint_2="Substitute n = 5: 5 * 5 = 25.",
             explanation="square(5) is called with n=5. The method returns n*n = 5*5 = 25, which is then printed."),

        dict(topic="Methods & Arrays", difficulty=2,
             prompt="What is the output?\n\nint[] nums = new int[3];\nSystem.out.println(nums[0]);",
             options=["0", "null", "Error", "undefined"],
             correct_answer="0",
             hint_1="Java initialises numeric arrays with default values automatically.",
             hint_2="The default value for all int array elements is 0.",
             explanation="new int[3] creates an array of 3 integers, each automatically set to 0. Java always initialises array elements to their default value — 0 for int, false for boolean, null for objects."),

        dict(topic="OOP", difficulty=2,
             prompt="What does 'this' refer to inside a Java method?",
             options=["The current object instance", "The parent class", "The method itself", "The class definition"],
             correct_answer="The current object instance",
             hint_1="'this' is a reference — but a reference to what specifically?",
             hint_2="It refers to the object on which the current method was called.",
             explanation="'this' is a reference to the current object instance. It's useful for distinguishing between instance variables and parameters that share the same name."),

        dict(topic="OOP", difficulty=2,
             prompt="Which access modifier makes a field accessible only within its own class?",
             options=["private", "public", "protected", "default"],
             correct_answer="private",
             hint_1="This is the most restrictive of the four access levels.",
             hint_2="Only code inside the same class can read or modify private members.",
             explanation="private restricts access to the declaring class only. public allows access from anywhere. protected allows subclasses and same-package access. Default (no modifier) allows same-package access."),

        # ══ TIER 3 — Medium ══

        dict(topic="Java Basics", difficulty=3,
             prompt="What is the output?\n\nint x = 5;\nx += 3;\nx *= 2;\nSystem.out.println(x);",
             options=["16", "13", "11", "10"],
             correct_answer="16",
             hint_1="Apply the compound operators in order, step by step.",
             hint_2="x starts at 5. += 3 gives 8. *= 2 gives 16.",
             explanation="x += 3 means x = x + 3, so x becomes 8. Then x *= 2 means x = x * 2, so x becomes 16. Compound operators always use the current value of x."),

        dict(topic="Java Basics", difficulty=3,
             prompt="What is the output?\n\nint a = 10;\nint b = 3;\nSystem.out.println(a / b);\nSystem.out.println(a % b);",
             options=["3 then 1", "3.33 then 1", "3 then 0", "4 then 1"],
             correct_answer="3 then 1",
             hint_1="Integer division truncates; % gives the remainder.",
             hint_2="10 / 3 = 3 (truncated). 10 % 3 = 1 (what's left over).",
             explanation="10 / 3 = 3 with remainder 1. Integer division drops the decimal, giving 3. The modulo 10 % 3 = 10 - (3×3) = 1."),

        dict(topic="Control Flow", difficulty=3,
             prompt="What is printed?\n\nfor (int i = 0; i < 5; i++) {\n    if (i == 3) break;\n    System.out.print(i + \" \");\n}",
             options=["0 1 2", "0 1 2 3", "0 1 2 3 4", "1 2 3"],
             correct_answer="0 1 2",
             hint_1="break exits the loop when the condition i == 3 is met.",
             hint_2="When i = 3, break fires before the print statement executes.",
             explanation="For i = 0, 1, 2 the print runs normally. When i = 3, the if condition is true and break exits the loop immediately — before printing. So 3 never appears."),

        dict(topic="Control Flow", difficulty=3,
             prompt="What does this print?\n\nfor (int i = 0; i < 5; i++) {\n    if (i % 2 == 0) continue;\n    System.out.print(i + \" \");\n}",
             options=["1 3", "0 2 4", "1 2 3 4", "0 1 2 3 4"],
             correct_answer="1 3",
             hint_1="continue skips the rest of the loop body for that iteration only.",
             hint_2="Even numbers (0, 2, 4) trigger continue, skipping the print for those iterations.",
             explanation="When i is even, continue jumps to the next iteration, skipping the print. When i is odd (1, 3), the condition is false so continue is skipped and the print runs."),

        dict(topic="Control Flow", difficulty=3,
             prompt="What is the output?\n\nint x = 10;\nswitch (x) {\n    case 10: System.out.println(\"Ten\");\n    case 20: System.out.println(\"Twenty\");\n    default: System.out.println(\"Other\");\n}",
             options=["Ten Twenty Other", "Ten", "Ten Twenty", "Other"],
             correct_answer="Ten Twenty Other",
             hint_1="What happens in a switch without break statements?",
             hint_2="Without break, Java falls through from a matched case into all subsequent cases.",
             explanation="Java switch falls through by default — after matching case 10 and printing Ten, execution continues into case 20 (Twenty) and default (Other) because there are no break statements."),

        dict(topic="Methods & Arrays", difficulty=3,
             prompt="What is printed?\n\nstatic int add(int a, int b) {\n    return a + b;\n}\n\nint result = add(3, add(2, 4));\nSystem.out.println(result);",
             options=["9", "7", "6", "Error"],
             correct_answer="9",
             hint_1="Evaluate the innermost method call first.",
             hint_2="add(2, 4) returns 6. Then add(3, 6) returns 9.",
             explanation="Java evaluates arguments before passing them. add(2, 4) = 6 is computed first, then add(3, 6) = 9. This is normal inside-out evaluation of nested calls."),

        dict(topic="Methods & Arrays", difficulty=3,
             prompt="What is the output?\n\nint[] a = {1, 2, 3, 4, 5};\nint sum = 0;\nfor (int n : a) {\n    sum += n;\n}\nSystem.out.println(sum);",
             options=["15", "10", "5", "12"],
             correct_answer="15",
             hint_1="The enhanced for loop visits every element in the array.",
             hint_2="Add each element: 1 + 2 + 3 + 4 + 5.",
             explanation="The for-each loop iterates over each element and adds it to sum. 1+2+3+4+5 = 15. This is equivalent to a traditional for loop with an index."),

        dict(topic="Methods & Arrays", difficulty=3,
             prompt="What does this print?\n\nstatic void change(int x) {\n    x = 99;\n}\n\nint n = 5;\nchange(n);\nSystem.out.println(n);",
             options=["5", "99", "0", "Error"],
             correct_answer="5",
             hint_1="Java passes primitives by value — the method gets its own copy.",
             hint_2="Changing x inside the method has no effect on the original n.",
             explanation="Java is pass-by-value for primitives. The method receives a copy of n's value. Setting x = 99 inside change() only affects the local copy — n in the caller is untouched."),

        dict(topic="OOP", difficulty=3,
             prompt="Given:\n\nclass Animal {\n    String name;\n    Animal(String n) { name = n; }\n}\n\nAnimal a = new Animal(\"Cat\");\nSystem.out.println(a.name);",
             options=["Cat", "null", "Animal", "Error"],
             correct_answer="Cat",
             hint_1="Trace what the constructor does with its argument.",
             hint_2="The constructor assigns name = n, and n = \"Cat\".",
             explanation="new Animal(\"Cat\") calls the constructor with n=\"Cat\". The body sets name = n, so the instance variable name becomes \"Cat\". a.name then prints Cat."),

        dict(topic="OOP", difficulty=3,
             prompt="What is the output?\n\nclass Counter {\n    int count = 0;\n    void increment() { count++; }\n}\n\nCounter c = new Counter();\nc.increment();\nc.increment();\nSystem.out.println(c.count);",
             options=["2", "0", "1", "Error"],
             correct_answer="2",
             hint_1="Both calls are on the same object c.",
             hint_2="count starts at 0. Two increments give 2.",
             explanation="count is an instance field initialised to 0. Each call to increment() does count++ on the same object c. After two calls, count = 2."),

        dict(topic="OOP", difficulty=3,
             prompt="What is encapsulation in Java?",
             options=["Hiding data and exposing it through methods", "Inheriting from a parent class", "Creating multiple objects from one class", "Overriding methods in subclasses"],
             correct_answer="Hiding data and exposing it through methods",
             hint_1="Think about private fields with public getters and setters.",
             hint_2="The goal is to control how internal state is accessed and modified.",
             explanation="Encapsulation means declaring fields as private and providing public getter/setter methods to control access. This protects the object's internal state from being directly manipulated by outside code."),

        # ══ TIER 4 — Hard ══

        dict(topic="Java Basics", difficulty=4,
             prompt="What is the output?\n\nint x = 1;\nSystem.out.println(x++ + ++x);",
             options=["4", "3", "2", "5"],
             correct_answer="4",
             hint_1="Post-increment uses the value then increments; pre-increment increments then uses.",
             hint_2="x++ returns 1 and makes x=2. ++x then makes x=3 and returns 3. 1+3=4.",
             explanation="x++ returns 1 (current value), then x becomes 2. ++x immediately increments x to 3 and returns 3. The expression evaluates to 1 + 3 = 4."),

        dict(topic="Java Basics", difficulty=4,
             prompt="What is printed?\n\nString s = \"Java\";\nSystem.out.println(s.substring(1, 3));",
             options=["av", "ava", "Jav", "va"],
             correct_answer="av",
             hint_1="substring(start, end) is start-inclusive and end-exclusive.",
             hint_2="Indices: J=0, a=1, v=2, a=3. Characters at 1 and 2 are 'a' and 'v'.",
             explanation="substring(1, 3) returns characters at indices 1 and 2 (index 3 is excluded). Index 1 is 'a', index 2 is 'v' — so the result is \"av\"."),

        dict(topic="Java Basics", difficulty=4,
             prompt="What is the output?\n\nint x = 5;\nSystem.out.println(x > 3 ? \"High\" : \"Low\");\nSystem.out.println(x > 10 ? \"High\" : \"Low\");",
             options=["High then Low", "Low then High", "High then High", "Low then Low"],
             correct_answer="High then Low",
             hint_1="Evaluate each ternary expression independently.",
             hint_2="5 > 3 is true → High. 5 > 10 is false → Low.",
             explanation="The ternary operator (condition ? valueIfTrue : valueIfFalse) evaluates independently each time. 5 > 3 = true → High. 5 > 10 = false → Low."),

        dict(topic="Control Flow", difficulty=4,
             prompt="What is the output?\n\nint count = 0;\nfor (int i = 1; i <= 10; i++) {\n    if (i % 3 == 0) count++;\n}\nSystem.out.println(count);",
             options=["3", "4", "2", "10"],
             correct_answer="3",
             hint_1="Find values between 1 and 10 that divide evenly by 3.",
             hint_2="i = 3, 6, and 9 each satisfy i % 3 == 0.",
             explanation="The multiples of 3 in range 1–10 are 3, 6, and 9. Each one increments count. Final value: count = 3."),

        dict(topic="Control Flow", difficulty=4,
             prompt="What does this nested loop print?\n\nfor (int i = 1; i <= 2; i++) {\n    for (int j = 1; j <= 2; j++) {\n        System.out.print(i + \"\" + j + \" \");\n    }\n}",
             options=["11 12 21 22", "11 21 12 22", "12 12 21 22", "11 12 22 21"],
             correct_answer="11 12 21 22",
             hint_1="The outer loop controls i; the inner loop runs fully for each value of i.",
             hint_2="i=1: j runs 1,2 → 11,12. i=2: j runs 1,2 → 21,22.",
             explanation="For each value of i, j iterates completely. i=1,j=1 → 11; i=1,j=2 → 12; i=2,j=1 → 21; i=2,j=2 → 22. Result: 11 12 21 22."),

        dict(topic="Methods & Arrays", difficulty=4,
             prompt="What is the output?\n\nstatic void swap(int[] arr, int i, int j) {\n    int temp = arr[i];\n    arr[i] = arr[j];\n    arr[j] = temp;\n}\n\nint[] a = {1, 2, 3};\nswap(a, 0, 2);\nSystem.out.println(a[0] + \" \" + a[2]);",
             options=["3 1", "1 3", "3 3", "1 1"],
             correct_answer="3 1",
             hint_1="Arrays are objects — the method receives a reference to the same array.",
             hint_2="After swap: a[0] gets the old a[2]=3, and a[2] gets the old a[0]=1.",
             explanation="Unlike primitives, arrays are passed by reference. The method modifies the original array. After swap(a, 0, 2): a[0]=3, a[1]=2, a[2]=1. Printing a[0] and a[2] gives 3 1."),

        dict(topic="Methods & Arrays", difficulty=4,
             prompt="What is method overloading?",
             options=["Multiple methods with the same name but different parameter lists", "A method that calls itself", "Replacing a parent method in a subclass", "A method with no return type"],
             correct_answer="Multiple methods with the same name but different parameter lists",
             hint_1="The methods share a name but differ in their signatures.",
             hint_2="Different parameter types or count = overloading.",
             explanation="Overloading lets you define multiple methods with the same name, as long as their parameter lists differ in type, number, or order. The compiler picks the right one based on the call arguments."),

        dict(topic="OOP", difficulty=4,
             prompt="What is the output?\n\nclass Shape {\n    String type() { return \"Shape\"; }\n}\nclass Circle extends Shape {\n    String type() { return \"Circle\"; }\n}\n\nShape s = new Circle();\nSystem.out.println(s.type());",
             options=["Circle", "Shape", "Error", "null"],
             correct_answer="Circle",
             hint_1="The variable type is Shape, but what is the actual object stored in it?",
             hint_2="Java resolves method calls at runtime based on the actual object type.",
             explanation="s is declared as Shape but holds a Circle object. Java uses dynamic dispatch — method calls are resolved at runtime on the actual object. Circle.type() returns \"Circle\". This is polymorphism."),

        dict(topic="OOP", difficulty=4,
             prompt="What does 'super()' do inside a subclass constructor?",
             options=["Calls the parent class constructor", "Creates a new parent object", "Overrides the parent method", "Calls the current class constructor"],
             correct_answer="Calls the parent class constructor",
             hint_1="'super' refers to the parent class.",
             hint_2="super() in a constructor invokes the parent's constructor.",
             explanation="super() explicitly calls the parent class constructor. It must appear as the first statement if used. Java inserts an implicit super() call if you omit it, assuming the parent has a no-arg constructor."),

        dict(topic="OOP", difficulty=4,
             prompt="What is the output?\n\nclass Animal {\n    String sound() { return \"...\"; }\n}\nclass Dog extends Animal {\n    String sound() { return \"Woof\"; }\n}\nclass Cat extends Animal {\n    String sound() { return \"Meow\"; }\n}\n\nAnimal[] animals = {new Dog(), new Cat(), new Dog()};\nfor (Animal a : animals) {\n    System.out.print(a.sound() + \" \");\n}",
             options=["Woof Meow Woof", "... ... ...", "Woof Woof Meow", "Error"],
             correct_answer="Woof Meow Woof",
             hint_1="Each object calls its own overridden sound() method.",
             hint_2="Array order: Dog, Cat, Dog. Dog → Woof, Cat → Meow.",
             explanation="Each element in the animals array has its own runtime type. Java's method overriding means each object calls its own sound(). Dog → Woof, Cat → Meow, Dog → Woof."),

        # ══ TIER 5 — Very Hard ══

        dict(topic="Java Basics", difficulty=5,
             prompt="What is the output?\n\nString a = new String(\"hello\");\nString b = new String(\"hello\");\nSystem.out.println(a == b);\nSystem.out.println(a.equals(b));",
             options=["false then true", "true then true", "false then false", "true then false"],
             correct_answer="false then true",
             hint_1="== compares references (memory addresses). equals() compares content.",
             hint_2="new String() always creates a distinct object in memory.",
             explanation="== checks if two references point to the same object. new String() creates two separate heap objects, so == is false. equals() compares the character content of the strings, which is identical — so true."),

        dict(topic="Java Basics", difficulty=5,
             prompt="What is the output?\n\nint x = 1;\nSystem.out.println(x++ + ++x);",
             options=["4", "3", "2", "5"],
             correct_answer="4",
             hint_1="Post-increment returns then increments; pre-increment increments then returns.",
             hint_2="x++ returns 1 (x→2). ++x makes x=3 and returns 3. 1+3=4.",
             explanation="x++ evaluates to 1 (current value) and then x becomes 2. ++x then increments x to 3 and evaluates to 3. The full expression is 1 + 3 = 4."),

        dict(topic="Control Flow", difficulty=5,
             prompt="What is the output?\n\nint result = 0;\nfor (int i = 1; i <= 4; i++) {\n    result += i * i;\n}\nSystem.out.println(result);",
             options=["30", "10", "24", "20"],
             correct_answer="30",
             hint_1="Add the square of each number from 1 to 4.",
             hint_2="1² + 2² + 3² + 4² = 1 + 4 + 9 + 16.",
             explanation="Each iteration adds i*i to result. Summing: 1 + 4 + 9 + 16 = 30. This is the sum of squares formula applied manually."),

        dict(topic="Control Flow", difficulty=5,
             prompt="What is the output?\n\nint x = 6;\nString result = (x > 10) ? \"Big\" : (x > 3) ? \"Medium\" : \"Small\";\nSystem.out.println(result);",
             options=["Medium", "Big", "Small", "Error"],
             correct_answer="Medium",
             hint_1="Evaluate the outer ternary condition first.",
             hint_2="x > 10 is false, so evaluate the nested ternary: x > 3 is true → Medium.",
             explanation="The outer condition x > 10 is false, so we take the else branch: (x > 3) ? \"Medium\" : \"Small\". Since 6 > 3 is true, the result is \"Medium\". Nested ternaries evaluate inside-out."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="What is the output?\n\nstatic int factorial(int n) {\n    if (n == 0) return 1;\n    return n * factorial(n - 1);\n}\n\nSystem.out.println(factorial(4));",
             options=["24", "12", "16", "10"],
             correct_answer="24",
             hint_1="Trace the recursion: factorial(4) = 4 * factorial(3) ...",
             hint_2="Unwind: factorial(0)=1, ×1=1, ×2=2, ×3=6, ×4=24.",
             explanation="Each call multiplies n by the result of n-1. The base case factorial(0) = 1. Unwinding: 1×1=1, 2×1=2, 3×2=6, 4×6=24."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="What is the output?\n\nstatic int[] doubled(int[] arr) {\n    int[] result = new int[arr.length];\n    for (int i = 0; i < arr.length; i++) {\n        result[i] = arr[i] * 2;\n    }\n    return result;\n}\n\nint[] a = {1, 3, 5};\nint[] b = doubled(a);\nSystem.out.println(b[0] + b[1] + b[2]);",
             options=["18", "9", "16", "6"],
             correct_answer="18",
             hint_1="doubled() creates a new array with each element multiplied by 2.",
             hint_2="{1,3,5} doubled = {2,6,10}. Sum = 2+6+10.",
             explanation="doubled() allocates a new array and fills it with doubled values. {1,3,5} → {2,6,10}. b[0]+b[1]+b[2] = 2+6+10 = 18. The original array a is unchanged."),

        dict(topic="OOP", difficulty=5,
             prompt="What is the output?\n\nclass A {\n    int x = 10;\n    int getX() { return x; }\n}\nclass B extends A {\n    int x = 20;\n    int getX() { return x; }\n}\n\nA obj = new B();\nSystem.out.println(obj.x);\nSystem.out.println(obj.getX());",
             options=["10 then 20", "20 then 20", "10 then 10", "20 then 10"],
             correct_answer="10 then 20",
             hint_1="Fields and methods behave differently with inheritance.",
             hint_2="Field access uses the declared type (A). Method calls use the runtime type (B).",
             explanation="Fields are not polymorphic — obj.x is resolved by the declared type A, giving 10. Methods are polymorphic — obj.getX() is resolved by the runtime type B, giving 20. This is a key distinction in Java inheritance."),

        dict(topic="OOP", difficulty=5,
             prompt="What does the 'final' keyword do when applied to a method?",
             options=["Prevents the method from being overridden in subclasses", "Makes the method run only once", "Prevents the method from being called outside the class", "Makes all parameters inside the method constant"],
             correct_answer="Prevents the method from being overridden in subclasses",
             hint_1="'final' on a method restricts what subclasses can do with it.",
             hint_2="The method is still inherited and callable — it just can't be replaced.",
             explanation="A final method can be inherited and called normally, but no subclass can override it. This is used to lock down critical behaviour. Compare with final class (can't be subclassed) and final variable (can't be reassigned)."),

        dict(topic="OOP", difficulty=5,
             prompt="What is the difference between an interface and an abstract class in Java?",
             options=[
                 "An interface cannot have method implementations; abstract classes can",
                 "An interface can be instantiated; abstract classes cannot",
                 "Abstract classes support multiple inheritance; interfaces do not",
                 "There is no difference — they are interchangeable"
             ],
             correct_answer="An interface cannot have method implementations; abstract classes can",
             hint_1="Think about what each construct is allowed to define.",
             hint_2="Abstract classes can have both concrete and abstract methods.",
             explanation="Abstract classes can have concrete (implemented) methods, constructors, and fields alongside abstract ones. Interfaces (pre-Java 8) only declare method signatures — no implementations. A class can implement multiple interfaces but only extend one abstract class."),

        dict(topic="OOP", difficulty=5,
             prompt="What is the output?\n\ninterface Greet {\n    String hello();\n}\n\nclass English implements Greet {\n    public String hello() { return \"Hello\"; }\n}\n\nclass Spanish implements Greet {\n    public String hello() { return \"Hola\"; }\n}\n\nGreet g = new Spanish();\nSystem.out.println(g.hello());",
             options=["Hola", "Hello", "Error", "null"],
             correct_answer="Hola",
             hint_1="g holds a Spanish object — which hello() gets called?",
             hint_2="The runtime type determines which implementation runs.",
             explanation="g is declared as the interface Greet but holds a Spanish instance. Java resolves the hello() call at runtime on the actual object type — Spanish.hello() returns \"Hola\". This is interface polymorphism."),

        # ══ TIER 5 — Exam Style (multi-method traces, defined concepts) ══

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="A number is called NUDE if it is divisible by every one of its digits.\nFor example, 124 is nude because 124÷1=124, 124÷2=62, and 124÷4=31 — all exact.\n\nConsider this implementation:\n\nstatic boolean isNude(int n) {\n    int temp = n;\n    while (temp > 0) {\n        int digit = temp % 10;\n        if (digit == 0 || n % digit != 0)\n            return false;\n        temp = temp / 10;\n    }\n    return true;\n}\n\nWhich of these correctly describes what the method does?",
             options=[
                 "Returns true only if n is divisible by every one of its digits, treating digit 0 as automatically failing",
                 "Returns true if any digit divides n evenly",
                 "Returns true if n is divisible by the sum of its digits",
                 "Returns true if all digits are the same"
             ],
             correct_answer="Returns true only if n is divisible by every one of its digits, treating digit 0 as automatically failing",
             hint_1="Trace what happens when digit == 0. Does it pass or fail?",
             hint_2="The loop extracts digits right-to-left using % 10. If any digit is 0 or doesn't divide n evenly, it returns false immediately.",
             explanation="The method extracts each digit using temp % 10. If the digit is 0 (which would cause division by zero) or n % digit != 0, it returns false. Only if all digits pass does it return true. This correctly implements the nude number definition."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="A number is called NUDE if it is divisible by every one of its non-zero digits.\n124 is nude (124÷1=124, 124÷2=62, 124÷4=31). 125 is not nude (125÷2 has a remainder).\n\nFour students wrote isNude(). Which implementation is correct?\n\nA: if (n % digit == 0) return true;\nB: if (digit != 0 && n % digit == 0) continue; else return false;\nC: if (digit == 0 || n % digit != 0) return false;\nD: return n % digit == 0;",
             options=[
                 "C — returns false on 0 digit or non-divisor, otherwise continues checking all digits",
                 "A — returns true as soon as any digit divides n",
                 "B — skips zero digits but returns false too early",
                 "D — only checks the last digit"
             ],
             correct_answer="C — returns false on 0 digit or non-divisor, otherwise continues checking all digits",
             hint_1="A correct implementation must check EVERY digit, not just the first one that passes.",
             hint_2="A returns true too early (on first match). D only ever checks one digit. C is the only one that rejects on failure and continues on success.",
             explanation="C is the correct inner-loop body. It rejects immediately if a digit is 0 (undefined division) or doesn't divide n evenly, and continues to the next digit otherwise. A short-circuits incorrectly on the first passing digit. D only evaluates one digit. B has a logic flaw that causes premature returns."),

        dict(topic="Control Flow", difficulty=5,
             prompt="A number is a ZYGODROME if every digit appears in a run of 2 or more identical consecutive digits.\n1122 is a zygodrome (11 then 22). 1123 is not (the 3 appears alone).\n\nWhat does this method return for input 1122?\n\nstatic boolean isZygodrome(int n) {\n    String s = Integer.toString(n);\n    int i = 0;\n    while (i < s.length()) {\n        int j = i;\n        while (j < s.length() && s.charAt(j) == s.charAt(i))\n            j++;\n        if (j - i < 2) return false;\n        i = j;\n    }\n    return true;\n}",
             options=["true", "false", "Throws an exception", "Infinite loop"],
             correct_answer="true",
             hint_1="Trace the outer loop: i starts at 0. The inner loop finds how far the current run extends.",
             hint_2="For '1122': i=0, inner loop finds j=2 (run of two 1s, length 2 ≥ 2 ✓). Then i=2, inner loop finds j=4 (run of two 2s ✓). Loop ends, returns true.",
             explanation="The method scans runs of identical characters. For each run starting at i, j advances while characters match. If the run length (j-i) is less than 2, it returns false. For 1122: run '11' has length 2, run '22' has length 2 — both pass, so true is returned."),

        dict(topic="Control Flow", difficulty=5,
             prompt="A number is a ZYGODROME if every digit appears in a run of 2 or more identical consecutive digits.\n112277 is a zygodrome. 1234 is not. 1112 is not (the final 2 appears only once).\n\nWhat does the isZygodrome method (same as previous question) return for input 1112?\n\nstatic boolean isZygodrome(int n) {\n    String s = Integer.toString(n);\n    int i = 0;\n    while (i < s.length()) {\n        int j = i;\n        while (j < s.length() && s.charAt(j) == s.charAt(i))\n            j++;\n        if (j - i < 2) return false;\n        i = j;\n    }\n    return true;\n}",
             options=["false", "true", "Throws StringIndexOutOfBoundsException", "Infinite loop"],
             correct_answer="false",
             hint_1="Trace the string '1112'. The first run is '111' (length 3, passes). What is the second run?",
             hint_2="After the run of three 1s, i moves to index 3. The character there is '2', and j only reaches 4. Run length = 1, which is less than 2, so it returns false.",
             explanation="For '1112': the first run '111' has length 3 ≥ 2, so it passes. Then i=3, s.charAt(3)='2', the inner loop finds j=4 (only one '2'). j-i = 1 < 2, so the method returns false. 1112 is not a zygodrome."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="A proper divisor of a number n is any positive divisor of n other than n itself.\nFor example, the proper divisors of 12 are 1, 2, 3, 4, 6.\n\nWhat does this method return for n=12?\n\nstatic int sumOfProperDivisors(int n) {\n    int sum = 0;\n    for (int i = 1; i < n; i++) {\n        if (n % i == 0)\n            sum += i;\n    }\n    return sum;\n}",
             options=["16", "12", "28", "14"],
             correct_answer="16",
             hint_1="List the proper divisors of 12 and add them up.",
             hint_2="Proper divisors of 12: 1, 2, 3, 4, 6. Sum = 1+2+3+4+6 = 16.",
             explanation="The loop checks every i from 1 to n-1. If n % i == 0, i is a proper divisor and gets added to sum. For n=12: divisors are 1, 2, 3, 4, 6. Sum = 16."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="A number is PERFECT if the sum of its proper divisors equals itself.\nA number is ABUNDANT if the sum exceeds it. DEFICIENT if the sum is less.\nProper divisors of n are all positive divisors excluding n itself.\n\nGiven sumOfProperDivisors(n) works correctly, what does this return for n=6?\n\nstatic String classify(int n) {\n    int s = sumOfProperDivisors(n);\n    if (s == n) return \"Perfect\";\n    if (s > n)  return \"Abundant\";\n    return \"Deficient\";\n}",
             options=["Perfect", "Abundant", "Deficient", "Admirable"],
             correct_answer="Perfect",
             hint_1="Work out the proper divisors of 6 first.",
             hint_2="Proper divisors of 6 are 1, 2, 3. Sum = 6. Since sum == n, it's Perfect.",
             explanation="The proper divisors of 6 are 1, 2, and 3 (all divisors except 6 itself). Their sum is 6, which equals n. So the condition s == n is true and the method returns 'Perfect'. 6 is the smallest perfect number."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="A number is ABUNDANT if the sum of its proper divisors is greater than the number itself.\n12 is abundant because its proper divisors (1,2,3,4,6) sum to 16 > 12.\n\nWhat does classify(8) return?\n\nstatic String classify(int n) {\n    int s = sumOfProperDivisors(n);\n    if (s == n) return \"Perfect\";\n    if (s > n)  return \"Abundant\";\n    return \"Deficient\";\n}\n\n(sumOfProperDivisors correctly returns the sum of all divisors of n excluding n itself)",
             options=["Deficient", "Perfect", "Abundant", "0"],
             correct_answer="Deficient",
             hint_1="Find the proper divisors of 8 and sum them.",
             hint_2="Proper divisors of 8: 1, 2, 4. Sum = 7. Since 7 < 8, it's Deficient.",
             explanation="The proper divisors of 8 are 1, 2, and 4. Sum = 7. Since 7 < 8, the first two conditions are false, and the method falls through to return 'Deficient'."),

        dict(topic="Control Flow", difficulty=5,
             prompt="Trace the following program carefully.\n\nstatic int mystery(int n) {\n    int result = 0;\n    int i = 1;\n    while (i < n) {\n        if (n % i == 0)\n            result += i;\n        i++;\n    }\n    return result;\n}\n\nstatic void main() {\n    int x = mystery(12);\n    if (x == 12)       System.out.println(\"Perfect\");\n    else if (x > 12)   System.out.println(\"Abundant\");\n    else               System.out.println(\"Deficient\");\n}",
             options=["Abundant", "Perfect", "Deficient", "0"],
             correct_answer="Abundant",
             hint_1="mystery(12) computes the sum of proper divisors of 12.",
             hint_2="Proper divisors of 12: 1,2,3,4,6. Sum = 16. Since 16 > 12, the output is Abundant.",
             explanation="mystery(n) sums all i from 1 to n-1 where n % i == 0 — that's the sum of proper divisors. For n=12: 1+2+3+4+6 = 16. Since 16 > 12, the else-if branch prints 'Abundant'."),

        dict(topic="OOP", difficulty=5,
             prompt="Trace this multi-class program:\n\nclass Vehicle {\n    int speed = 60;\n    String describe() { return \"Vehicle at \" + speed; }\n}\n\nclass Car extends Vehicle {\n    int speed = 100;\n    String describe() { return \"Car at \" + speed; }\n}\n\nclass Truck extends Vehicle {\n    String describe() { return \"Truck at \" + speed; }\n}\n\nVehicle[] v = { new Car(), new Truck(), new Vehicle() };\nfor (Vehicle x : v) {\n    System.out.println(x.describe());\n}",
             options=[
                 "Car at 100 / Truck at 60 / Vehicle at 60",
                 "Car at 60 / Truck at 60 / Vehicle at 60",
                 "Vehicle at 60 / Vehicle at 60 / Vehicle at 60",
                 "Car at 100 / Truck at 100 / Vehicle at 60"
             ],
             correct_answer="Car at 100 / Truck at 60 / Vehicle at 60",
             hint_1="Car overrides both speed (field) and describe(). Truck overrides describe() but NOT speed.",
             hint_2="Truck.describe() uses 'speed' — but Truck has no speed field, so it inherits Vehicle's speed=60. Car.describe() uses its own speed=100.",
             explanation="Car overrides describe() and has its own speed=100 field, so it prints 'Car at 100'. Truck overrides describe() but has no speed field — it inherits speed=60 from Vehicle, printing 'Truck at 60'. Vehicle.describe() uses its own speed=60."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="Trace this program and determine the output:\n\nstatic int getDigit(int number, int digitNumber) {\n    int digits = Integer.toString(number).length();\n    if (digitNumber < 1 || digitNumber > digits) return -1;\n    return Integer.toString(number).charAt(digitNumber - 1) - '0';\n}\n\nstatic int getNumberOfDigits(int number) {\n    return Integer.toString(number).length();\n}\n\nSystem.out.println(getDigit(4729, 2));\nSystem.out.println(getDigit(4729, 5));\nSystem.out.println(getNumberOfDigits(4729));",
             options=["7 then -1 then 4", "2 then -1 then 4", "4 then -1 then 4", "7 then 0 then 4"],
             correct_answer="7 then -1 then 4",
             hint_1="digitNumber 1 = first (leftmost) digit. '4729' as a string: index 0='4', index 1='7', index 2='2', index 3='9'.",
             hint_2="getDigit(4729, 2) returns charAt(1)-'0' = '7'-'0' = 7. getDigit(4729, 5) returns -1 (only 4 digits). getNumberOfDigits returns 4.",
             explanation="getDigit converts the number to a string and returns charAt(digitNumber-1) minus '0' (to convert char to int). For 4729: digitNumber=2 → charAt(1) = '7' → 7. digitNumber=5 is out of range → -1. getNumberOfDigits('4729') has length 4."),

        dict(topic="Control Flow", difficulty=5,
             prompt="A number is ADMIRABLE if you can subtract exactly twice one of its proper divisors from the sum of all proper divisors and get the number itself.\nFor example: proper divisors of 12 are 1,2,3,4,6 (sum=16). 16 - 2×2 = 12. So 12 is admirable.\n\nWhat does this method return for n=12?\n\nstatic boolean isAdmirable(int n) {\n    int s = sumOfProperDivisors(n);\n    int i = 1;\n    while (i < n) {\n        if (n % i == 0 && s - 2 * i == n)\n            return true;\n        i++;\n    }\n    return false;\n}",
             options=["true", "false", "Throws ArithmeticException", "Infinite loop"],
             correct_answer="true",
             hint_1="sumOfProperDivisors(12) = 16. Try each proper divisor i and check if 16 - 2*i == 12.",
             hint_2="When i=2: 16 - 2*2 = 12 == n. The condition is true, so the method returns true immediately.",
             explanation="The method tries every proper divisor i of n. It checks if subtracting 2*i from the sum of proper divisors gives n. For n=12, sum=16, and i=2 satisfies 16-4=12. So isAdmirable(12) returns true."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="Trace this complete program:\n\nstatic int computeNextDivisor(int n, int last) {\n    for (int i = last + 1; i < n; i++)\n        if (n % i == 0) return i;\n    return -1;\n}\n\nstatic void main() {\n    int n = 10;\n    int divisor = computeNextDivisor(n, 0);\n    int sum = 0;\n    while (divisor != -1) {\n        sum += divisor;\n        divisor = computeNextDivisor(n, divisor);\n    }\n    System.out.println(sum);\n}",
             options=["8", "10", "18", "7"],
             correct_answer="8",
             hint_1="computeNextDivisor finds the next divisor of n after 'last'. Trace it for n=10 starting from 0.",
             hint_2="Divisors of 10 less than 10: 1, 2, 5. Sum = 1+2+5 = 8.",
             explanation="computeNextDivisor(10, 0) returns 1. Then 2. Then 5. Then -1 (no more). The while loop accumulates 1+2+5 = 8. Note: 10 itself is excluded because the loop runs while i < n."),

        dict(topic="OOP", difficulty=5,
             prompt="Trace this program carefully:\n\nclass Shape {\n    double area() { return 0; }\n    void print() { System.out.println(\"Area: \" + area()); }\n}\n\nclass Circle extends Shape {\n    double r;\n    Circle(double r) { this.r = r; }\n    double area() { return 3 * r * r; }\n}\n\nclass Square extends Shape {\n    double s;\n    Square(double s) { this.s = s; }\n    double area() { return s * s; }\n}\n\nShape[] shapes = { new Circle(2), new Square(3) };\nfor (Shape sh : shapes) { sh.print(); }",
             options=[
                 "Area: 12.0 / Area: 9.0",
                 "Area: 0.0 / Area: 0.0",
                 "Area: 12.0 / Area: 0.0",
                 "Error: cannot call area() on Shape"
             ],
             correct_answer="Area: 12.0 / Area: 9.0",
             hint_1="print() is defined in Shape and calls this.area(). Which area() gets called for each object?",
             hint_2="Because area() is overridden, Java calls Circle.area() and Square.area() at runtime. Circle: 3×2×2=12. Square: 3×3=9.",
             explanation="print() is inherited by both Circle and Square. When it calls area(), Java uses dynamic dispatch — Circle.area() returns 3×2×2=12.0, Square.area() returns 3×3=9.0. This is the Template Method pattern — the base class defines the structure, subclasses fill in the detail."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="Consider these two methods:\n\nstatic int sumDigits(int n) {\n    if (n < 10) return n;\n    return n % 10 + sumDigits(n / 10);\n}\n\nstatic boolean isSelfDivisor(int n) {\n    int temp = n;\n    while (temp > 0) {\n        int d = temp % 10;\n        if (d == 0 || n % d != 0) return false;\n        temp /= 10;\n    }\n    return true;\n}\n\nSystem.out.println(sumDigits(248));\nSystem.out.println(isSelfDivisor(248));",
             options=["14 then true", "14 then false", "248 then true", "4 then false"],
             correct_answer="14 then true",
             hint_1="sumDigits: extract last digit with %10, recurse on /10. isSelfDivisor: check if n divisible by each digit.",
             hint_2="sumDigits(248) = 8+4+2 = 14. Digits of 248: 8,4,2. 248÷8=31 ✓, 248÷4=62 ✓, 248÷2=124 ✓. All pass → true.",
             explanation="sumDigits(248): 8 + sumDigits(24) → 8+4+sumDigits(2) → 8+4+2 = 14. isSelfDivisor(248): digits 8,4,2 all divide 248 evenly. Returns true. Output: 14 then true."),

        dict(topic="Methods & Arrays", difficulty=5,
             prompt="Consider this recursive method:\n\nstatic int sumDigits(int n) {\n    if (n < 10) return n;\n    return n % 10 + sumDigits(n / 10);\n}\n\nWhat does sumDigits(327) return?",
             options=["12", "327", "3", "23"],
             correct_answer="12",
             hint_1="The method extracts the last digit (n%10) and recurses on the rest (n/10).",
             hint_2="327%10=7, recurse(32): 32%10=2, recurse(3): base case returns 3. Unwind: 3+2+7=12.",
             explanation="sumDigits(327): returns 7 + sumDigits(32). sumDigits(32): returns 2 + sumDigits(3). sumDigits(3): base case, returns 3. Unwinding: 3+2=5, 5+7=12."),

        dict(topic="OOP", difficulty=5,
             prompt="Trace this program and select the correct output:\n\nclass Counter {\n    private int count;\n    Counter(int start) { this.count = start; }\n    void increment(int by) { count += by; }\n    int get() { return count; }\n}\n\nstatic int applyTwice(Counter c, int amount) {\n    c.increment(amount);\n    c.increment(amount);\n    return c.get();\n}\n\nCounter a = new Counter(5);\nCounter b = new Counter(10);\nSystem.out.println(applyTwice(a, 3));\nSystem.out.println(b.get());",
             options=["11 then 10", "11 then 16", "5 then 10", "8 then 10"],
             correct_answer="11 then 10",
             hint_1="applyTwice passes the Counter object by reference — changes to c inside the method affect the original.",
             hint_2="a starts at 5. Two increments of 3 → 5+3+3=11. b is never touched — stays at 10.",
             explanation="Counter is an object, so applyTwice receives a reference to a. It calls increment(3) twice on a: 5→8→11. get() returns 11. b is a separate object, never modified — get() returns 10. Output: 11 then 10."),
    ]

    for q in questions:
        db.add(Question(
            topic=q["topic"],
            difficulty=q["difficulty"],
            prompt=q["prompt"],
            options_json=json.dumps(q["options"]),
            correct_answer=q["correct_answer"],
            hint_1=q["hint_1"],
            hint_2=q["hint_2"],
            explanation=q["explanation"],
        ))
    db.commit()
    print(f"[seed] Seeded {len(questions)} questions across 5 difficulty tiers.")